export const SAVE_CHARACTER_LOCALSTORAGE = "SAVE_CHARACTER_LOCALSTORAGE";
export const LOAD_CHARACTER_LOCALSTORAGE = "LOAD_CHARACTER_LOCALSTORAGE";
export const LOAD_CHARACTER_HOOK = "LOAD_CHARACTER_HOOK";
export const RESET_CHARACTER = "RESET_CHARACTER";
